#! /bin/sh
# Script to bring a network (tap) device for qemu up.
# The idea is to add the tap device to the same bridge
# as we have default routing to.

# config for in container environment
if [ -f "/var/.indocker" ]; then
	VETH=`ip route | awk '/default/ {print $5}'`
	TAP=$1

	mkdir -p /var/share
	# vm host is in container
	touch /var/share/.hostindocker

	# get container eth0 network config
	echo "ipaddress `ifconfig $VETH | awk '/inet/ {print $2}'`" > /var/share/net.cfg
	echo "netmask `ifconfig $VETH | awk '/netmask/ {print $4}'`" >> /var/share/net.cfg
	echo "gateway `ip route | awk '/default/ {print $3}'`" >> /var/share/net.cfg
	# get container dns config
	cp /etc/resolv.conf /var/share/resolv.conf

	ip link set $TAP up

	ip addr flush dev $VETH
	tc qdisc add dev $VETH ingress
	tc qdisc add dev $TAP ingress
	tc filter add dev $VETH parent ffff: protocol all u32 match u8 0 0 action mirred egress redirect dev $TAP
	tc filter add dev $TAP parent ffff: protocol all u32 match u8 0 0 action mirred egress redirect dev $VETH
	exit 0
fi

# in order to be able to find brctl
PATH=$PATH:/sbin:/usr/sbin
ip=$(which ip)

if [ -n "$ip" ]; then
   ip link set "$1" up
else
   brctl=$(which brctl)
   if [ ! "$ip" -o ! "$brctl" ]; then
     echo "W: $0: not doing any bridge processing: neither ip nor brctl utility not found" >&2
     exit 0
   fi
   ifconfig "$1" 0.0.0.0 up
fi

switch=$(ip route ls | \
    awk '/^default / {
          for(i=0;i<NF;i++) { if ($i == "dev") { print $(i+1); next; } }
         }'
        )

# only add the interface to default-route bridge if we
# have such interface (with default route) and if that
# interface is actually a bridge.
# It is possible to have several default routes too
for br in $switch; do
    if [ -d /sys/class/net/$br/bridge/. ]; then
        if [ -n "$ip" ]; then
          ip link set "$1" master "$br"
        else
          brctl addif $br "$1"
        fi
        exit	# exit with status of the previous command
    fi
done

echo "W: $0: no bridge for guest interface found" >&2
